version: '2'
volumes:
    etcher_cache:
    etcher_config:
    etcher_gnupg:
    etcher_pki:
    influxdb:
    grafana:
services:
  etcher:
    build: .
    privileged: true
    restart: always
    network_mode: host
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
    volumes:
      - 'etcher_cache:/root/.cache'
      - 'etcher_config:/root/.config/balena-etcher'
      - 'etcher_gnupg:/root/.gnupg'
      - 'etcher_pki:/root/.pki'
    tmpfs:
      - /host
      - /run
      - /tmp
      - /mnt
    environment:
      - 'UDEV=1'
      - 'ELECTRON_ENABLE_LOGGING=1'
      - 'BALENAELECTRONJS_OVERLAY_DELAY=4000'
      - 'BALENAELECTRONJS_SLEEP_BUTTON_POSITION=20,13'
      - 'BALENAELECTRONJS_WIFI_BUTTON_POSITION=114,13'
      - 'BALENAELECTRONJS_ZOOM_FACTOR=1.28'
      - 'BALENAELECTRONJS_BRIGHTNESS_FILTER=0.96'
      - 'BALENAELECTRONJS_MOUNTS_ROOT=/mnt'
      - 'BALENAELECTRONJS_CONSTRAINT_PATH=/mnt'
      - 'BALENAELECTRONJS_SCREENSAVER_DELAY_OVERRIDE=5'
      - 'BALENAELECTRONJS_UPDATES_ONLY_DURING_SCREENSAVER=1'
      - 'BALENAELECTRONJS_SCREENSAVER_ON_COMMAND=screensaver_on.sh'
      - 'BALENAELECTRONJS_SCREENSAVER_OFF_COMMAND=screensaver_off.sh'
  influxdb:
    restart: always
    build: ./etcher-pro-monitoring/influxdb
    network_mode: host
    volumes:
      - 'influxdb:/data'
  grafana:
    restart: always
    build: ./etcher-pro-monitoring/grafana
    network_mode: host
    volumes:
      - 'grafana:/data'
    environment:
      - 'GF_SERVER_HTTP_PORT=80'
      - 'GF_PATHS_PROVISIONING=/usr/src/app/provisioning'
      - 'GF_SESSION_PROVIDER=memory'
  collectd:
    build: ./etcher-pro-monitoring/collectd
    privileged: true
    restart: always
    network_mode: host
  beep:
    build: ./etcher-pro-monitoring/beep
    privileged: true
    restart: no
  benchmark:
    build: ./etcher-pro-monitoring/benchmark
    privileged: true
    restart: always
    network_mode: host
